//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Editor.Assets.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] animations {
            get {
                object obj = ResourceManager.GetObject("animations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] animatronics {
            get {
                object obj = ResourceManager.GetObject("animatronics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial {
            get {
                object obj = ResourceManager.GetObject("Arial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cameraeditor {
            get {
                object obj = ResourceManager.GetObject("cameraeditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] createproject {
            get {
                object obj = ResourceManager.GetObject("createproject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] extensions {
            get {
                object obj = ResourceManager.GetObject("extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gameinfo {
            get {
                object obj = ResourceManager.GetObject("gameinfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] menuseditor {
            get {
                object obj = ResourceManager.GetObject("menuseditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] officeeditor {
            get {
                object obj = ResourceManager.GetObject("officeeditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openproject {
            get {
                object obj = ResourceManager.GetObject("openproject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scripteditor {
            get {
                object obj = ResourceManager.GetObject("scripteditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sounds {
            get {
                object obj = ResourceManager.GetObject("sounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] templates {
            get {
                object obj = ResourceManager.GetObject("templates", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
